# Generated by Django 3.1.1 on 2021-05-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='cms/icons')),
                ('logo', models.ImageField(upload_to='cms/logos')),
                ('header_title', models.CharField(max_length=50)),
            ],
        ),
    ]
