# Generated by Django 3.1.1 on 2021-05-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20210521_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=50, verbose_name='Title')),
                ('slug', models.CharField(help_text='Slug', max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='footerdescription',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.template'),
        ),
        migrations.AddField(
            model_name='image',
            name='carrousel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.carrousel'),
        ),
        migrations.AddField(
            model_name='menu',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.template'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='cms/images/'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title', max_length=50, verbose_name='Title')),
                ('body', models.TextField(blank=True, max_length=200, null=True)),
                ('carrousel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.carrousel')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page'),
        ),
    ]
