# Generated by Django 3.1.1 on 2021-05-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_capacitation', models.IntegerField(blank=True, verbose_name='Codigo de capacitacion')),
                ('approved', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, null=True, verbose_name='Esta aprobado?')),
            ],
            options={
                'verbose_name': 'Assistance',
                'verbose_name_plural': 'Assistances',
            },
        ),
        migrations.CreateModel(
            name='Capacitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre capacitacion')),
                ('address', models.CharField(blank=True, max_length=30, verbose_name='Direccion')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.assistance', verbose_name='Codigo')),
            ],
            options={
                'verbose_name': 'Capacitation',
                'verbose_name_plural': 'Capacitations',
            },
        ),
        migrations.CreateModel(
            name='CapacityCertificate',
            fields=[
                ('consecutive', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='consecutive')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Generation date certificate')),
                ('QR_path', models.URLField(blank=True, null=True, verbose_name='QR path')),
            ],
            options={
                'verbose_name': 'Capacity Certificate',
                'verbose_name_plural': 'Capacity Certificates',
            },
        ),
        migrations.CreateModel(
            name='CertificateAssistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(blank=True, max_length=30, verbose_name='Consecutivo')),
                ('date', models.DateField(auto_now_add=True)),
                ('qr_url', models.URLField(blank=True, null=True, verbose_name='Ruta qr')),
                ('assistance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.assistance', verbose_name='Asistencia')),
            ],
            options={
                'verbose_name': 'Certificate Assistance',
                'verbose_name_plural': 'Certificate Assistances',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Nombre de ciudad')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='ClientEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(blank=True, max_length=10, null=True, verbose_name='NIt')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de la empresa')),
                ('business_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Razon Social')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=10, null=True, verbose_name='Email')),
                ('adress', models.CharField(blank=True, max_length=30, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Client Entity',
                'verbose_name_plural': 'Client Entities',
            },
        ),
        migrations.CreateModel(
            name='ConcepType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='codigo')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de concepto')),
            ],
            options={
                'verbose_name': 'Type Concept',
                'verbose_name_plural': 'Type Concepts',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Type Document',
                'verbose_name_plural': 'Type Documents',
            },
        ),
        migrations.CreateModel(
            name='TypeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='codigo')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tipo de examen')),
            ],
            options={
                'verbose_name': 'Tipo Test',
                'verbose_name_plural': 'Type Tests',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=30, verbose_name='Resultado')),
                ('typetest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.typetest', verbose_name='TIpo de  examen')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='NOmbres')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellidos')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='telefono')),
                ('identification', models.IntegerField(blank=True, null=True, verbose_name='Número de identificación')),
                ('address', models.CharField(blank=True, max_length=30, verbose_name='Direccion')),
                ('job', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.city', verbose_name='Ciudad')),
                ('type_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.typedocument', verbose_name='TIpode documento')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=30, verbose_name='Universidad')),
                ('especiality', models.CharField(blank=True, max_length=30, verbose_name='Especialidad')),
                ('url', models.URLField(blank=True, max_length=30, verbose_name='Ruta firma')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Official',
                'verbose_name_plural': 'Officials',
            },
        ),
        migrations.CreateModel(
            name='Manipulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.cliententity', verbose_name='Empresa de cliente')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Manipulator',
                'verbose_name_plural': 'Manipulators',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(blank=True, max_length=10, null=True, verbose_name='NIt')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre de la empresa')),
                ('business_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Razon Social')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=10, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=30, verbose_name='Direccion')),
                ('service', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion de servicio')),
                ('capacitations', models.ManyToManyField(to='certificates.Capacitation')),
                ('official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.official', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm', models.CharField(blank=True, max_length=30, null=True, verbose_name='RM')),
                ('resolution', models.CharField(blank=True, max_length=30, verbose_name='Resolucion')),
                ('official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.official', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='CertificateDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(blank=True, max_length=10, null=True, verbose_name='Consecutivo')),
                ('date', models.DateField(auto_now_add=True)),
                ('diagnostic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Diagnostico')),
                ('certificateassitance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.certificateassistance', verbose_name='Tipo de concepto')),
                ('conceptype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.conceptype', verbose_name='Tipo de concepto')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.doctor', verbose_name='Doctor')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.entity', verbose_name='Empresa')),
                ('manipulator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.manipulator', verbose_name='Manipulador')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.test', verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Doctor Certificate',
                'verbose_name_plural': 'Doctor Certificates',
            },
        ),
        migrations.AddField(
            model_name='capacitation',
            name='official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.official', verbose_name='Funcionario'),
        ),
        migrations.AddField(
            model_name='assistance',
            name='assistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.manipulator', verbose_name='Asistente'),
        ),
    ]
