# Generated by Django 3.1.1 on 2021-05-23 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptype',
            options={'verbose_name': 'Concept Type', 'verbose_name_plural': 'Concept Types'},
        ),
        migrations.AlterModelOptions(
            name='typedocument',
            options={'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.AlterModelOptions(
            name='typetest',
            options={'verbose_name': 'Test Type', 'verbose_name_plural': 'Test Types'},
        ),
        migrations.RemoveField(
            model_name='capacitycertificate',
            name='QR_path',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='rm',
        ),
        migrations.RemoveField(
            model_name='official',
            name='especiality',
        ),
        migrations.AddField(
            model_name='capacitycertificate',
            name='qr_url',
            field=models.URLField(blank=True, null=True, verbose_name='Qr Url'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_record',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medical Record'),
        ),
        migrations.AddField(
            model_name='official',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Specialty Name'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='approved',
            field=models.CharField(blank=True, choices=[('SI', 'Yes'), ('NO', 'No')], max_length=2, null=True, verbose_name='Approved?'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='assistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.manipulator', verbose_name='Choose Manipulator'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='code_capacitation',
            field=models.IntegerField(blank=True, verbose_name='Capacitation Code'),
        ),
        migrations.AlterField(
            model_name='capacitation',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='capacitation',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.assistance', verbose_name='Choose Assistance'),
        ),
        migrations.AlterField(
            model_name='capacitation',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Capacitation Date'),
        ),
        migrations.AlterField(
            model_name='capacitation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacitacion Name'),
        ),
        migrations.AlterField(
            model_name='capacitycertificate',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Certificate Generation Date'),
        ),
        migrations.AlterField(
            model_name='certificateassistance',
            name='assistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.assistance', verbose_name='Choose Assistance'),
        ),
        migrations.AlterField(
            model_name='certificateassistance',
            name='consecutive',
            field=models.CharField(blank=True, max_length=30, verbose_name='Consecutive'),
        ),
        migrations.AlterField(
            model_name='certificateassistance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Certificate Of Assistance Date'),
        ),
        migrations.AlterField(
            model_name='certificateassistance',
            name='qr_url',
            field=models.URLField(blank=True, null=True, verbose_name='QR Code Url'),
        ),
        migrations.AlterField(
            model_name='certificatedoctor',
            name='certificateassitance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.certificateassistance', verbose_name='Choose Certificate Assistance'),
        ),
        migrations.AlterField(
            model_name='certificatedoctor',
            name='conceptype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.conceptype', verbose_name='Choose Concep Type'),
        ),
        migrations.AlterField(
            model_name='certificatedoctor',
            name='consecutive',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Consecutive'),
        ),
        migrations.AlterField(
            model_name='certificatedoctor',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Certificate Date'),
        ),
        migrations.AlterField(
            model_name='certificatedoctor',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagnostic'),
        ),
        migrations.AlterField(
            model_name='certificatedoctor',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.doctor', verbose_name='Choose Doctor'),
        ),
        migrations.AlterField(
            model_name='certificatedoctor',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.entity', verbose_name='Choose Entity'),
        ),
        migrations.AlterField(
            model_name='certificatedoctor',
            name='manipulator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.manipulator', verbose_name='Choose Manipulator'),
        ),
        migrations.AlterField(
            model_name='certificatedoctor',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.test', verbose_name='Choose Test Result'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='cliententity',
            name='adress',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='cliententity',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='cliententity',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='cliententity',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entity Name'),
        ),
        migrations.AlterField(
            model_name='cliententity',
            name='nit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nit (Tributary Identification Number)'),
        ),
        migrations.AlterField(
            model_name='cliententity',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='conceptype',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Concept Code'),
        ),
        migrations.AlterField(
            model_name='conceptype',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Concept Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.official', verbose_name='Choose Official'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='resolution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Resolution Number'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entity Name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='nit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nit (Tributary Identification Number)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.official', verbose_name='Choose Official'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='manipulator',
            name='birth',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='manipulator',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.cliententity', verbose_name='Choose Entity'),
        ),
        migrations.AlterField(
            model_name='manipulator',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.person', verbose_name='Choose Person'),
        ),
        migrations.AlterField(
            model_name='official',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.person', verbose_name='Choose Person'),
        ),
        migrations.AlterField(
            model_name='official',
            name='university',
            field=models.CharField(blank=True, max_length=100, verbose_name='University Name'),
        ),
        migrations.AlterField(
            model_name='official',
            name='url',
            field=models.URLField(blank=True, max_length=300, verbose_name='Signature Url'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.city', verbose_name='Choose City'),
        ),
        migrations.AlterField(
            model_name='person',
            name='identification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identification Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.typedocument', verbose_name='Choose Document Type'),
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(blank=True, max_length=100, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='test',
            name='typetest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.typetest', verbose_name='Choose Test Type'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Document Name'),
        ),
        migrations.AlterField(
            model_name='typetest',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Code'),
        ),
        migrations.AlterField(
            model_name='typetest',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Test Name'),
        ),
    ]
