# Generated by Django 3.1.1 on 2021-05-28 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20210523_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitation',
            name='capacity_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Intensidad de la capacitación'),
        ),
        migrations.AddField(
            model_name='certificateassistance',
            name='capacitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.capacitation', verbose_name='Capacitación'),
        ),
        migrations.AddField(
            model_name='certificateassistance',
            name='certificate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la Certificación'),
        ),
    ]
