# Generated by Django 3.1.1 on 2021-05-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20210528_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Address'),
        ),
    ]
