# Generated by Django 3.1.1 on 2021-05-29 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatedoctor',
            name='result',
        ),
        migrations.AddField(
            model_name='capacitycertificate',
            name='assistancecertificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.certificateassistance', verbose_name='Choose Official'),
        ),
        migrations.AddField(
            model_name='capacitycertificate',
            name='medicalcertificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatedoctor', verbose_name='Choose Official'),
        ),
        migrations.AddField(
            model_name='test',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatedoctor', verbose_name='Choose Test Type'),
        ),
        migrations.AlterField(
            model_name='official',
            name='url',
            field=models.ImageField(blank=True, upload_to='signatures', verbose_name='Signature Imagen'),
        ),
    ]
