name: BIOS CI/CD

on:
  pull_request:
    branches: 
      - master

  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-20.04
    env:
      DJANGO_SETTINGS_MODULE: "bios.settings.development"
    
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-versions: [ 3.8 ]
        django-versions: [ 3.1 ]

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        export "PATH=/home/runner/.local/bin:$PATH"
        python manage.py test

  deployment:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v1
      - name: Dokku deployment
        # Please check https://github.com/marketplace/actions/dokku-github-action
        uses: vitalyliber/dokku-github-action@v6.0
        env:
          # Dokku droplet private key. You must add the private key in your secrets.
          # This private key must not have a passphrase
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Dokku droplet IPv4
          HOST: 157.230.57.158
          # App name
          PROJECT: bios
